version: 2.0
jobs:
    py36:
        working_directory: ~/circleci
        docker:
            - image: continuumio/miniconda3
              environment:
                PYTHON_VER: 3.6.9

        steps:
            - checkout

            - run: |
                conda config --system --add channels conda-forge
                conda config --system --add channels coecms
                conda install conda-build conda-verify

            - run: |
                conda build conda

            - run: |
                mkdir ~/artefacts
                cp $(~/conda/bin/conda build conda --output) ~/artefacts

            - persist_to_workspace:
                root: ~/artefacts
                paths: '*'

    publish:
        working_directory: ~/circleci
        docker:
            - image: continuumio/miniconda3
        steps:
            - attach_workspace:
                at: ~/artefacts

            - run:
                anaconda --token "${ANACONDA_TOKEN}" upload --user "${ANACONDA_USER}" /artefacts/*.tar.bz2

workflows:
    version: 2
    build_and_publsh:
        jobs:
            - py36:
                filters:
                    tags:
                        only: /.*/

            - publish:
                requires:
                    - py36
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
